# Generated by Django 2.2.5 on 2020-02-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_classlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='teach_teacher',
            field=models.ManyToManyField(blank=True, related_name='teach_classes', to='web.UserInfo', verbose_name='讲师'),
        ),
    ]
