# Generated by Django 2.2.5 on 2020-02-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_consultrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='跟进日期'),
        ),
    ]
