# Generated by Django 2.2.5 on 2019-10-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20191023_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='URL的别名'),
        ),
    ]
