# Generated by Django 2.2.6 on 2019-10-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20191024_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=32, verbose_name='邮箱'),
        ),
    ]
